# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f6d37ca7280f8cb85562dc10eeea44fade718e923eb443bec0bbd4bad2bf1978d3cea121adde2258aa68e09feba9c951e5fa17083e62587a9c53e93bb0cc2fe

test:
  secret_key_base: 62343b3546cebaf9d02a78487528b0202b65b21de46490e7836ebeffc12038958f5c6fcfbb76d5433accbca3bc09dc5ce7eef465db0e682149a0e4debb0410a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
